version: "2"
services:
  cassandra:
    image: cassandra
    expose:
      - 80
    networks:
      - backend
    healthcheck:
      test: cqlsh
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  nodejsback:
    build: ./
    ports:
      - 7000:7000
    networks:
      - backend
    depends_on:
      cassandra:
        condition: service_healthy



networks:
  backend:
